### ISSUE TITLE
call TestJrnlWriteRead will crash

### ISSUE THREAD

**Issue by izouxv** [mit-pdos/go-journal#1]
hi 
i run testcase  [TestJrnlWriteRead](https://github.com/mit-pdos/go-journal/blob/deb3ebed7c1e2abafdda6606d1b68fcb6a386c1e/jrnl/jrnl_test.go#L34), it's crash
go version go1.22.2 darwin/arm64

**Comment by zeldovich** [comment]
Could you say more about the problem you're seeing?  I tried to run `go test ./jrnl -run=TestJrnlWriteRead -count=10000` on `go version go1.22.3 linux/amd64` but everything worked fine.

**Comment by izouxv** [comment]
hi
i try it again, it ok. 
thank you for your reply
